sudo: false
language: node_js
cache:
    - yarn
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
    - export PATH="$HOME/.yarn/bin:$PATH"
install:
    - yarn
script:
    - npx audit-ci -m
    - yarn run coverage-upload
